"use strict";this.default_ContributorServingCookieRefreshClientJs=this.default_ContributorServingCookieRefreshClientJs||{};(function(_){var window=this;
try{
var ba=function(a){a:{var b=aa;for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]},da=function(a,b){b=ca(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},ea=function(a){return Array.prototype.concat.apply([],arguments)},fa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},ha=function(a,b){for(var c=1;c<arguments.length;c++){var d=
arguments[c];if(m(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},ia=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)},ja=function(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c},ka=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];if(Array.isArray(d))for(var e=0;e<d.length;e+=8192)for(var f=ka.apply(null,ia(d,e,e+8192)),g=0;g<f.length;g++)b.push(f[g]);else b.push(d)}return b},
la=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ma="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},na=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},oa=na(this),
n=function(a,b){if(b)a:{var c=oa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ma(c,a,{configurable:!0,writable:!0,value:b})}};
n("Symbol",function(a){if(a)return a;var b=function(e,f){this.a=e;ma(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.a};var c=0,d=function(e){if(this instanceof d)throw new TypeError("b");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d});
n("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=oa[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ma(d.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(la(this))}})}return a});
var pa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},qa=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:la(a)}},ra="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},sa;
if("function"==typeof Object.setPrototypeOf)sa=Object.setPrototypeOf;else{var ta;a:{var ua={V:!0},va={};try{va.__proto__=ua;ta=va.V;break a}catch(a){}ta=!1}sa=ta?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}
var wa=sa,xa=function(a,b){a.prototype=ra(b.prototype);a.prototype.constructor=a;if(wa)wa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.D=b.prototype},ya=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
n("Array.prototype.keys",function(a){return a?a:function(){return ya(this,function(b){return b})}});n("Array.prototype.values",function(a){return a?a:function(){return ya(this,function(b,c){return c})}});n("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
n("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});n("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("e`includes");if(b instanceof RegExp)throw new TypeError("f`includes");return-1!==this.indexOf(b,c||0)}});
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var za=za||{},p=this||self,Aa=/^[\w+/_-]+[=]{0,2}$/,Ba=null,Ca=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&Aa.test(a)?a:""},Da=function(){},m=function(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length},Ea=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},Fa=function(a,b,c){return a.call.apply(a.bind,arguments)},Ga=function(a,b,c){if(!a)throw Error();
if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},r=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?r=Fa:r=Ga;return r.apply(null,arguments)},t=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(d,
e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}},Ha=function(a){return a};
var u=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};t(u,Error);u.prototype.name="CustomError";
var ca=function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ia=function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ja=function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};
var Ka=function(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}return b};
var La="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ma=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<La.length;f++)c=La[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Na;
var Qa=function(a,b){this.c=a===Oa&&b||"";this.f=Pa};Qa.prototype.b=!0;Qa.prototype.a=function(){return this.c};var Ra=function(a){return a instanceof Qa&&a.constructor===Qa&&a.f===Pa?a.c:"type_error:Const"},Pa={},Oa={};
var Ta=function(a,b){this.c=b===Sa?a:""};Ta.prototype.b=!0;Ta.prototype.a=function(){return this.c.toString()};
var Ya=function(a,b){a=Ua.exec(Va(a).toString());var c=a[3]||"";return Wa(a[1]+Xa("?",a[2]||"",b)+Xa("#",c,void 0))},Va=function(a){return a instanceof Ta&&a.constructor===Ta?a.c:"type_error:TrustedResourceUrl"},Ua=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Sa={},Wa=function(a){if(void 0===Na){var b=null;var c=p.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("ContributorServingCookieRefreshClientJs#html",{createHTML:Ha,createScript:Ha,createScriptURL:Ha})}catch(d){p.console&&p.console.error(d.message)}Na=
b}else Na=b}a=(b=Na)?b.createScriptURL(a):a;return new Ta(a,Sa)},Xa=function(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var g=e[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};
var Za=function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},$a=function(a,b){return a<b?-1:a>b?1:0};
var v=function(a,b){this.c=b===ab?a:""};v.prototype.b=!0;v.prototype.a=function(){return this.c.toString()};var bb=function(a){return a instanceof v&&a.constructor===v?a.c:"type_error:SafeUrl"},cb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,ab={};
var x;a:{var db=p.navigator;if(db){var eb=db.userAgent;if(eb){x=eb;break a}}x=""}
;var fb=function(a){var b;(b=a.ownerDocument&&a.ownerDocument.defaultView)&&b!=p?b=Ca(b.document):(null===Ba&&(Ba=Ca(p.document)),b=Ba);b&&a.setAttribute("nonce",b)},gb=function(a){var b=p.location;a instanceof v||a instanceof v||(a="object"==typeof a&&a.b?a.a():String(a),cb.test(a)||(a="about:invalid#zClosurez"),a=new v(a,ab));b.href=bb(a)};
var hb=function(a){hb[" "](a);return a};hb[" "]=Da;var jb=function(a,b){var c=ib;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};
var kb=-1!=x.indexOf("Opera"),y=-1!=x.indexOf("Trident")||-1!=x.indexOf("MSIE"),lb=-1!=x.indexOf("Edge"),mb=-1!=x.indexOf("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&-1==x.indexOf("Edge"))&&!(-1!=x.indexOf("Trident")||-1!=x.indexOf("MSIE"))&&-1==x.indexOf("Edge"),nb=-1!=x.toLowerCase().indexOf("webkit")&&-1==x.indexOf("Edge"),ob=function(){var a=p.document;return a?a.documentMode:void 0},pb;
a:{var qb="",rb=function(){var a=x;if(mb)return/rv:([^\);]+)(\)|;)/.exec(a);if(lb)return/Edge\/([\d\.]+)/.exec(a);if(y)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(nb)return/WebKit\/(\S+)/.exec(a);if(kb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();rb&&(qb=rb?rb[1]:"");if(y){var sb=ob();if(null!=sb&&sb>parseFloat(qb)){pb=String(sb);break a}}pb=qb}
var tb=pb,ib={},ub=function(a){return jb(a,function(){for(var b=0,c=Za(String(tb)).split("."),d=Za(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=$a(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||$a(0==g[2].length,0==h[2].length)||$a(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<=b})},vb;
if(p.document&&y){var wb=ob();vb=wb?wb:parseInt(tb,10)||void 0}else vb=void 0;var xb=vb;
var yb={},zb=null,Bb=function(a,b){void 0===b&&(b=0);Ab();b=yb[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,g=f?a[d+1]:0,h=d+2<a.length,k=h?a[d+2]:0,l=e>>2;e=(e&3)<<4|g>>4;g=(g&15)<<2|k>>6;k&=63;h||(k=64,f||(g=64));c.push(b[l],b[e],b[g]||"",b[k]||"")}return c.join("")},Db=function(a){var b=[];Cb(a,function(c){b.push(c)});return b},Cb=function(a,b){function c(k){for(;d<a.length;){var l=a.charAt(d++),q=zb[l];if(null!=q)return q;if(!/^[\s\xa0]*$/.test(l))throw Error("g`"+l);}return k}
Ab();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|f>>4);64!=g&&(b(f<<4&240|g>>2),64!=h&&b(g<<6&192|h))}},Ab=function(){if(!zb){zb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));yb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];void 0===zb[f]&&(zb[f]=e)}}}};
var z=function(){},Eb="function"==typeof Uint8Array,A=function(a,b,c,d){a.a=null;b||(b=[]);a.i=void 0;a.c=-1;a.j=b;a:{if(b=a.j.length){--b;var e=a.j[b];if(!(null===e||"object"!=typeof e||Array.isArray(e)||Eb&&e instanceof Uint8Array)){a.f=b-a.c;a.b=e;break a}}a.f=Number.MAX_VALUE}a.h={};if(c)for(b=0;b<c.length;b++)e=c[b],e<a.f?(e+=a.c,a.j[e]=a.j[e]||Fb):(Gb(a),a.b[e]=a.b[e]||Fb);if(d&&d.length)for(b=0;b<d.length;b++)Hb(a,d[b])},Fb=[],Gb=function(a){var b=a.f+a.c;a.j[b]||(a.b=a.j[b]={})},B=function(a,
b){if(b<a.f){b+=a.c;var c=a.j[b];return c===Fb?a.j[b]=[]:c}if(a.b)return c=a.b[b],c===Fb?a.b[b]=[]:c},D=function(a,b,c){a=B(a,b);return null==a?c:a},E=function(a,b,c){b<a.f?a.j[b+a.c]=c:(Gb(a),a.b[b]=c);return a},Ib=function(a,b,c){0!==c?E(a,b,c):b<a.f?a.j[b+a.c]=null:(Gb(a),delete a.b[b])},Hb=function(a,b){for(var c,d,e=0;e<b.length;e++){var f=b[e],g=B(a,f);null!=g&&(c=f,d=g,E(a,f,void 0))}return c?(E(a,c,d),c):0},F=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=B(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},
Jb=function(a,b){a.a||(a.a={});if(!a.a[1]){for(var c=B(a,1),d=[],e=0;e<c.length;e++)d[e]=new b(c[e]);a.a[1]=d}},G=function(a,b,c){a.a||(a.a={});var d=c?c.j:c;a.a[b]=c;return E(a,b,d)};z.prototype.g=Eb?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return Bb(this)};try{return JSON.stringify(this.j&&this.j,Kb)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.j&&this.j,Kb)};
var Kb=function(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)},Lb=function(a,b){return new a(b?JSON.parse(b):null)};z.prototype.toString=function(){return this.j.toString()};
var Ob=function(a){var b=new Mb;return b==a||!(!b||!a)&&b instanceof a.constructor&&Nb(b.j,a.j)},Pb=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!Nb(a[d],b[d]))return!1;return!0},Nb=function(a,b){if(a==b)return!0;if(!Ea(a)||!Ea(b))return"number"===typeof a&&isNaN(a)||"number"===typeof b&&isNaN(b)?String(a)==String(b):!1;if(a.constructor!=b.constructor)return!1;if(Eb&&a.constructor===Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=
b[c])return!1;return!0}if(a.constructor===Array){var d=void 0,e=void 0,f=Math.max(a.length,b.length);for(c=0;c<f;c++){var g=a[c],h=b[c];g&&g.constructor==Object&&(d=g,g=void 0);h&&h.constructor==Object&&(e=h,h=void 0);if(!Nb(g,h))return!1}return d||e?(d=d||{},e=e||{},Pb(d,e)):!0}if(a.constructor===Object)return Pb(a,b);throw Error("h");};
var Qb=function(a){A(this,a,null,null)};t(Qb,z);
var H=function(a){A(this,a,null,null)};t(H,z);var Rb=function(a){A(this,a,null,null)};t(Rb,z);var Sb=function(a){A(this,a,null,null)};t(Sb,z);var Tb=function(a){A(this,a,null,null)};t(Tb,z);var Ub=function(a){A(this,a,null,null)};t(Ub,z);var Vb=function(){var a=new Ub;return E(a,2,!0)},Wb=function(){var a=new H;var b=new Sb;b=E(b,1,!0);return G(a,3,b)};
var I=function(a){A(this,a,null,Xb)};t(I,z);var Xb=[[10,11,8,12,13,14,15,16,17,19,18,20]],J=function(a,b){var c=Xb[0];a.a||(a.a={});var d=b?b.j:b;a.a[8]=b;(b=Hb(a,c))&&8!==b&&void 0!==d&&(a.a&&b in a.a&&(a.a[b]=void 0),E(a,b,void 0));return E(a,8,d)};
var Yb=function(a){A(this,a,null,null)};t(Yb,z);
var Zb=function(a){A(this,a,null,null)};t(Zb,z);
var $b=function(){this.h=this.h;this.l=this.l};$b.prototype.h=!1;$b.prototype.g=function(){if(this.l)for(;this.l.length;)this.l.shift()()};
var ac=function(a,b){this.type=a;this.a=this.target=b;this.defaultPrevented=!1};ac.prototype.b=function(){this.defaultPrevented=!0};
var bc;(bc=!y)||(bc=9<=Number(xb));var cc=bc,dc=y&&!ub("9"),ec=function(){if(!p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{p.addEventListener("test",Da,b),p.removeEventListener("test",Da,b)}catch(c){}return a}();
var gc=function(a,b){ac.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.c=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;if(b=a.relatedTarget){if(mb){a:{try{hb(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=
null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:fc[a.pointerType]||"";this.c=a;a.defaultPrevented&&this.b()}};t(gc,ac);var fc={2:"touch",3:"pen",4:"mouse"};gc.prototype.b=function(){gc.D.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,dc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var hc="closure_listenable_"+(1E6*Math.random()|0),ic=0;
var jc=function(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.B=e;this.key=++ic;this.v=this.A=!1},kc=function(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.B=null};
var lc=function(a){this.src=a;this.a={};this.b=0};lc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=mc(a,b,d,e);-1<g?(b=a[g],c||(b.A=!1)):(b=new jc(b,this.src,f,!!d,e),b.A=c,a.push(b));return b};var nc=function(a,b){var c=b.type;c in a.a&&da(a.a[c],b)&&(kc(b),0==a.a[c].length&&(delete a.a[c],a.b--))},mc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.v&&f.listener==b&&f.capture==!!c&&f.B==d)return e}return-1};
var oc="closure_lm_"+(1E6*Math.random()|0),pc={},qc=0,sc=function(a,b,c,d,e){if(d&&d.once)rc(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)sc(a,b[f],c,d,e);else c=tc(c),a&&a[hc]?a.b.add(String(b),c,!1,Ea(d)?!!d.capture:!!d,e):uc(a,b,c,!1,d,e)},uc=function(a,b,c,d,e,f){if(!b)throw Error("i");var g=Ea(e)?!!e.capture:!!e,h=vc(a);h||(a[oc]=h=new lc(a));c=h.add(b,c,d,g,f);if(!c.a){d=wc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)ec||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(xc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("j");qc++}},wc=function(){var a=yc,b=cc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},rc=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)rc(a,b[f],c,d,e);else c=tc(c),a&&a[hc]?a.b.add(String(b),c,!0,Ea(d)?!!d.capture:!!d,e):uc(a,b,c,!0,d,e)},zc=function(a,b,c,d,e){if(Array.isArray(b))for(var f=
0;f<b.length;f++)zc(a,b[f],c,d,e);else(d=Ea(d)?!!d.capture:!!d,c=tc(c),a&&a[hc])?(a=a.b,b=String(b).toString(),b in a.a&&(f=a.a[b],c=mc(f,c,d,e),-1<c&&(kc(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.a[b],a.b--)))):a&&(a=vc(a))&&(b=a.a[b.toString()],a=-1,b&&(a=mc(b,c,d,e)),(c=-1<a?b[a]:null)&&Ac(c))},Ac=function(a){if("number"!==typeof a&&a&&!a.v){var b=a.src;if(b&&b[hc])nc(b.b,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(xc(c),
d):b.addListener&&b.removeListener&&b.removeListener(d);qc--;(c=vc(b))?(nc(c,a),0==c.b&&(c.src=null,b[oc]=null)):kc(a)}}},xc=function(a){return a in pc?pc[a]:pc[a]="on"+a},Cc=function(a,b,c,d){var e=!0;if(a=vc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.v&&(f=Bc(f,d),e=e&&!1!==f)}return e},Bc=function(a,b){var c=a.listener,d=a.B||a.src;a.A&&Ac(a);return c.call(d,b)},yc=function(a,b){if(a.v)return!0;if(!cc){if(!b)a:{b=["window","event"];for(var c=p,
d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new gc(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.a;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;0<=e;e--){b.a=d[e];var f=Cc(d[e],a,!0,b);c=c&&f}for(e=0;e<d.length;e++)b.a=d[e],f=Cc(d[e],a,!1,b),c=c&&f}return c}return Bc(a,new gc(b,this))},vc=function(a){a=a[oc];return a instanceof lc?a:null},
Dc="__closure_events_fn_"+(1E9*Math.random()>>>0),tc=function(a){if("function"===typeof a)return a;a[Dc]||(a[Dc]=function(b){return a.handleEvent(b)});return a[Dc]};
var K=function(){$b.call(this);this.b=new lc(this);this.S=this;this.G=null};t(K,$b);K.prototype[hc]=!0;K.prototype.addEventListener=function(a,b,c,d){sc(this,a,b,c,d)};K.prototype.removeEventListener=function(a,b,c,d){zc(this,a,b,c,d)};
var L=function(a,b){var c,d=a.G;if(d)for(c=[];d;d=d.G)c.push(d);a=a.S;d=b.type||b;if("string"===typeof b)b=new ac(b,a);else if(b instanceof ac)b.target=b.target||a;else{var e=b;b=new ac(d,a);Ma(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.a=c[f];e=Ec(g,d,!0,b)&&e}g=b.a=a;e=Ec(g,d,!0,b)&&e;e=Ec(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.a=c[f],e=Ec(g,d,!1,b)&&e};
K.prototype.g=function(){K.D.g.call(this);if(this.b){var a=this.b,b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,kc(d[e]);delete a.a[c];a.b--}}this.G=null};var Ec=function(a,b,c,d){b=a.b.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.v&&g.capture==c){var h=g.listener,k=g.B||g.src;g.A&&nc(a.b,g);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};
var Fc=function(){};Fc.prototype.a=null;var Hc=function(a){var b;(b=a.a)||(b={},Gc(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};
var Ic,Jc=function(){};t(Jc,Fc);var Kc=function(a){return(a=Gc(a))?new ActiveXObject(a):new XMLHttpRequest},Gc=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("k");}return a.b};Ic=new Jc;
var M=function(a,b){this.b={};this.a=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("l");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof M)for(c=a.o(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};M.prototype.m=function(){Lc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};M.prototype.o=function(){Lc(this);return this.a.concat()};
var Lc=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];N(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],N(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};M.prototype.get=function(a,b){return N(this.b,a)?this.b[a]:b};M.prototype.set=function(a,b){N(this.b,a)||(this.c++,this.a.push(a));this.b[a]=b};M.prototype.forEach=function(a,b){for(var c=this.o(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
var N=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Mc=function(a){if(a.m&&"function"==typeof a.m)return a.m();if("string"===typeof a)return a.split("");if(m(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},Nc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(m(a)||"string"===typeof a)Ia(a,b,void 0);else{if(a.o&&"function"==typeof a.o)var c=a.o();else if(a.m&&"function"==typeof a.m)c=void 0;else if(m(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<
d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]=e;d=Mc(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var Oc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},Pc=function(a){this.a=a||p.document||document};
var Qc=function(a,b,c){if("function"===typeof a)c&&(a=r(a,c));else if(a&&"function"==typeof a.handleEvent)a=r(a.handleEvent,a);else throw Error("n");return 2147483647<Number(b)?-1:p.setTimeout(a,b||0)};
var Rc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Sc=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var O=function(a){K.call(this);this.headers=new M;this.C=a||null;this.c=!1;this.u=this.a=null;this.F="";this.f=this.K=this.i=this.J=!1;this.H=0;this.s=null;this.M="";this.I=this.O=!1};t(O,K);var Tc=/^https?$/i,Uc=["POST","PUT"],Vc=[];O.prototype.T=function(){this.h||(this.h=!0,this.g());da(Vc,this)};
var Zc=function(a,b,c){var d={"Content-Type":"text/plain"};if(a.a)throw Error("o`"+a.F+"`"+b);a.F=b;a.J=!1;a.c=!0;a.a=a.C?Kc(a.C):Kc(Ic);a.u=a.C?Hc(a.C):Hc(Ic);a.a.onreadystatechange=r(a.L,a);try{a.K=!0,a.a.open("POST",String(b),!0),a.K=!1}catch(f){Wc(a);return}b=c||"";var e=new M(a.headers);d&&Nc(d,function(f,g){e.set(g,f)});d=ba(e.o());c=p.FormData&&b instanceof p.FormData;!(0<=ca(Uc,"POST"))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,g){this.a.setRequestHeader(g,
f)},a);a.M&&(a.a.responseType=a.M);"withCredentials"in a.a&&a.a.withCredentials!==a.O&&(a.a.withCredentials=a.O);try{Xc(a),0<a.H&&(a.I=Yc(a.a),a.I?(a.a.timeout=a.H,a.a.ontimeout=r(a.N,a)):a.s=Qc(a.N,a.H,a)),a.i=!0,a.a.send(b),a.i=!1}catch(f){Wc(a)}},Yc=function(a){return y&&ub(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},aa=function(a){return"content-type"==a.toLowerCase()};O.prototype.N=function(){"undefined"!=typeof za&&this.a&&(L(this,"timeout"),this.abort(8))};
var Wc=function(a){a.c=!1;a.a&&(a.f=!0,a.a.abort(),a.f=!1);$c(a);ad(a)},$c=function(a){a.J||(a.J=!0,L(a,"complete"),L(a,"error"))};O.prototype.abort=function(){this.a&&this.c&&(this.c=!1,this.f=!0,this.a.abort(),this.f=!1,L(this,"complete"),L(this,"abort"),ad(this))};O.prototype.g=function(){this.a&&(this.c&&(this.c=!1,this.f=!0,this.a.abort(),this.f=!1),ad(this,!0));O.D.g.call(this)};O.prototype.L=function(){this.h||(this.K||this.i||this.f?bd(this):this.U())};O.prototype.U=function(){bd(this)};
var bd=function(a){if(a.c&&"undefined"!=typeof za&&(!a.u[1]||4!=(a.a?a.a.readyState:0)||2!=cd(a)))if(a.i&&4==(a.a?a.a.readyState:0))Qc(a.L,0,a);else if(L(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.c=!1;try{var b=cd(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=String(a.F).match(Rc)[1]||null;if(!f&&p.self&&p.self.location){var g=p.self.location.protocol;f=g.substr(0,g.length-1)}e=!Tc.test(f?
f.toLowerCase():"")}d=e}d?(L(a,"complete"),L(a,"success")):$c(a)}finally{ad(a)}}},ad=function(a,b){if(a.a){Xc(a);var c=a.a,d=a.u[0]?Da:null;a.a=null;a.u=null;b||L(a,"ready");try{c.onreadystatechange=d}catch(e){}}},Xc=function(a){a.a&&a.I&&(a.a.ontimeout=null);a.s&&(p.clearTimeout(a.s),a.s=null)},cd=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};
var dd=function(a){var b=void 0===b?{}:b;this.a=a?new v(Va(Ya(Wa(B(a,4)||""),b)).toString(),ab):null},P=function(a,b){if(a.a){E(b,9,Date.now());a=bb(a.a);b=b.g();var c=new O;Vc.push(c);c.b.add("ready",c.T,!0,void 0,void 0);Zc(c,a,b)}};
var ed=function(a){A(this,a,null,null)};t(ed,z);
var Mb=function(a){A(this,a,null,null)};t(Mb,z);var fd=function(a){A(this,a,null,null)};t(fd,z);var gd=function(a){A(this,a,null,null)};t(gd,z);var hd=function(a){A(this,a,null,null)};t(hd,z);
var Q=function(a){this.a=a||{cookie:""}};Q.prototype.set=function(a,b,c){var d=!1;if("object"===typeof c){var e=c.Y;d=c.Z||!1;var f=c.domain||void 0;var g=c.path||void 0;var h=c.P}if(/[;=\s]/.test(a))throw Error("p`"+a);if(/[;\r\n]/.test(b))throw Error("q`"+b);void 0===h&&(h=-1);this.a.cookie=a+"="+b+(f?";domain="+f:"")+(g?";path="+g:"")+(0>h?"":0==h?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*h)).toUTCString())+(d?";secure":"")+(null!=e?";samesite="+e:"")};
Q.prototype.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=Za(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};Q.prototype.o=function(){return id(this).keys};Q.prototype.m=function(){return id(this).values};var id=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=Za(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var jd=function(a,b,c){a=new Q(a);a.get(b);a.set(b,"",{P:0,path:"/",domain:c})};
var ld=function(a){a=kd(a);try{return a?Lb(Mb,a):null}catch(b){return null}},md=function(a){return(a=(new Q(a)).get("DATA_USE_CONSENT",""))?a:null},kd=function(a){return(a=(new Q(a)).get("FCCDCF",""))?a:null},nd=function(a){var b=ld(a);if(!b)return md(a);b=F(b,gd,3);if(!b||null==B(b,1))return md(a);a=B(b,2);var c=Date.now();if(a){if(c<a||c>a+33696E6)return null}else return null;return B(b,1)};
var pd=function(a){A(this,a,od,null)};t(pd,z);var od=[1,2,3,4];
var qd=function(a,b){this.a=a;this.b=b},sd=function(a){rd(a,"FCCDCF",a.b);rd(a,"DATA_USE_CONSENT",a.b)},td=function(a){a=kd(a.a);if(!a)return new Mb;try{return Lb(Mb,a)}catch(b){return new Mb}},ud=function(a,b,c){c=void 0===c?33696E3:c;Ob(b)?jd(a.a,"FCCDCF",a.b):(rd(a,"FCCDCF",a.b),b=b.g(),(new Q(a.a)).set("FCCDCF",b,{P:c,path:"/",domain:a.b}))},rd=function(a,b,c){if(c)for(c=c.split(".");2<=c.length;)jd(a.a,b,c.join(".")),c.shift();else jd(a.a,b,c)};
var R=function(a,b){this.b=a|0;this.a=b|0},vd=function(a){return 4294967296*a.a+(a.b>>>0)};R.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("r`"+a);var b=this.a>>21;if(0==b||-1==b&&(0!=this.b||-2097152!=this.a))return b=vd(this),10==a?""+b:b.toString(a);b=14-(a>>2);var c=Math.pow(a,b),d=S(c,c/4294967296);c=wd(this,d);d=Math.abs(vd(this.add(T(xd(c,d)))));var e=10==a?""+d:d.toString(a);e.length<b&&(e="0000000000000".substr(e.length-b)+e);d=vd(c);return(10==a?d:d.toString(a))+e};
var yd=function(a){return 0==a.b&&0==a.a},zd=function(a,b){return a.b==b.b&&a.a==b.a},Ad=function(a,b){return a.a==b.a?a.b==b.b?0:a.b>>>0>b.b>>>0?1:-1:a.a>b.a?1:-1},T=function(a){var b=~a.b+1|0;return S(b,~a.a+!b|0)};R.prototype.add=function(a){var b=this.a>>>16,c=this.a&65535,d=this.b>>>16,e=a.a>>>16,f=a.a&65535,g=a.b>>>16;a=(this.b&65535)+(a.b&65535);g=(a>>>16)+(d+g);d=g>>>16;d+=c+f;b=(d>>>16)+(b+e)&65535;return S((g&65535)<<16|a&65535,b<<16|d&65535)};
var xd=function(a,b){if(yd(a))return a;if(yd(b))return b;var c=a.a>>>16,d=a.a&65535,e=a.b>>>16;a=a.b&65535;var f=b.a>>>16,g=b.a&65535,h=b.b>>>16;b=b.b&65535;var k=a*b;var l=(k>>>16)+e*b;var q=l>>>16;l=(l&65535)+a*h;q+=l>>>16;q+=d*b;var w=q>>>16;q=(q&65535)+e*h;w+=q>>>16;q=(q&65535)+a*g;w=w+(q>>>16)+(c*b+d*h+e*g+a*f)&65535;return S((l&65535)<<16|k&65535,w<<16|q&65535)},wd=function(a,b){if(yd(b))throw Error("s");if(0>a.a){if(zd(a,Bd)){if(zd(b,Cd)||zd(b,Dd))return Bd;if(zd(b,Bd))return Cd;var c=1;if(0==
c)c=a;else{var d=a.a;c=32>c?S(a.b>>>c|d<<32-c,d>>c):S(d>>c-32,0<=d?0:-1)}c=wd(c,b);d=1;if(0!=d){var e=c.b;c=32>d?S(e<<d,c.a<<d|e>>>32-d):S(0,e<<d-32)}if(zd(c,Ed))return 0>b.a?Cd:Dd;a=a.add(T(xd(b,c)));return c.add(wd(a,b))}return 0>b.a?wd(T(a),T(b)):T(wd(T(a),b))}if(yd(a))return Ed;if(0>b.a)return zd(b,Bd)?Ed:T(wd(a,T(b)));for(d=Ed;0<=Ad(a,b);){c=Math.max(1,Math.floor(vd(a)/vd(b)));e=Math.ceil(Math.log(c)/Math.LN2);e=48>=e?1:Math.pow(2,e-48);for(var f=Fd(c),g=xd(f,b);0>g.a||0<Ad(g,a);)c-=e,f=Fd(c),
g=xd(f,b);yd(f)&&(f=Cd);d=d.add(f);a=a.add(T(g))}return d};R.prototype.and=function(a){return S(this.b&a.b,this.a&a.a)};R.prototype.or=function(a){return S(this.b|a.b,this.a|a.a)};R.prototype.xor=function(a){return S(this.b^a.b,this.a^a.a)};var Fd=function(a){return 0<a?0x7fffffffffffffff<=a?Gd:new R(a,a/4294967296):0>a?-9223372036854775808>=a?Bd:T(new R(-a,-a/4294967296)):Ed},S=function(a,b){return new R(a,b)},Ed=S(0,0),Cd=S(1,0),Dd=S(-1,-1),Gd=S(4294967295,2147483647),Bd=S(0,2147483648);
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
/*

 Copyright 2013 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Hd=function(a){u.call(this,a)};t(Hd,u);var Id=function(a){u.call(this,a)};t(Id,Hd);
/*

 Copyright 2012 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Jd=function(a){var b=[];Ia(a,function(c){b.push(c>>>24&255);b.push(c>>>16&255);b.push(c>>>8&255);b.push(c&255)});return b},Kd=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];b&=("number"==typeof d&&0<=d&&255>=d&&0==d-Math.floor(d))|0}return 1==b};
var Ld=function(){this.a=null},Md=function(){this.a=null};t(Md,Ld);
var Nd=function(){};
var Od=function(){this.b=-1};
var Pd=function(){this.b=64;this.a=[];this.l=[];this.s=[];this.i=[];this.i[0]=128;for(var a=1;a<this.b;++a)this.i[a]=0;this.h=this.f=0;this.reset()};t(Pd,Od);Pd.prototype.reset=function(){this.a[0]=1732584193;this.a[1]=4023233417;this.a[2]=2562383102;this.a[3]=271733878;this.a[4]=3285377520;this.h=this.f=0};
var Qd=function(a,b,c){c||(c=0);var d=a.s;if("string"===typeof b)for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.a[0];c=a.a[1];var g=a.a[2],h=a.a[3],k=a.a[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=h^c&(g^h);var l=1518500249}else f=c^g^h,l=1859775393;else 60>e?(f=c&g|h&(c|g),l=2400959708):
(f=c^g^h,l=3395469782);f=(b<<5|b>>>27)+f+k+l+d[e]&4294967295;k=h;h=g;g=(c<<30|c>>>2)&4294967295;c=b;b=f}a.a[0]=a.a[0]+b&4294967295;a.a[1]=a.a[1]+c&4294967295;a.a[2]=a.a[2]+g&4294967295;a.a[3]=a.a[3]+h&4294967295;a.a[4]=a.a[4]+k&4294967295};
Pd.prototype.c=function(a,b){if(null!=a){void 0===b&&(b=a.length);for(var c=b-this.b,d=0,e=this.l,f=this.f;d<b;){if(0==f)for(;d<=c;)Qd(this,a,d),d+=this.b;if("string"===typeof a)for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.b){Qd(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.b){Qd(this,e);f=0;break}}this.f=f;this.h+=b}};
Pd.prototype.g=function(){var a=[],b=8*this.h;56>this.f?this.c(this.i,56-this.f):this.c(this.i,this.b-(this.f-56));for(var c=this.b-1;56<=c;c--)this.l[c]=b&255,b/=256;Qd(this,this.l);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.a[c]>>d&255,++b;return a};
/*

 Copyright 2014 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Rd=function(a,b){return(-(a>b|0)|0)&(a^b)^b};
/*

 Copyright 2011 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var U=function(a){this.a=[];if(void 0!==a){if(!("function"===typeof p.Uint8Array&&a instanceof Uint8Array||Kd(a)))throw new Id("Input should be a byte array.");for(var b=a.length,c=Array((b+2)/3|0),d=0;0<=b;b-=3)c[d++]=a[b-1]&255|(a[b-2]&255)<<8|(a[b-3]&255)<<16;this.a=c}this.b=0},V=function(a){var b=new U;b.a.length=a;return b},Sd=function(a){var b=new U;b.a=fa(a);return b},Td=function(a){if(0>a||281474976710656<a)throw new Id("Argument must be a valid integer.");var b=new U;do b.a.push(a&16777215),
a=Math.floor(a/16777216);while(0<a);return b},Ud=function(a,b,c){c=-c|0;for(var d=Rd(a.a.length,b.a.length),e=V(d),f=0;f<d;++f)e.a[f]=c&(a.a[f]^b.a[f]);for(f=0;f<d;++f)e.a[f]^=b.a[f];return e},Vd=function(a){for(var b=a.a.length,c=0,d=Array(3*b);0<b;--b)d[c++]=a.a[b-1]>>>16&255,d[c++]=a.a[b-1]>>>8&255,d[c++]=a.a[b-1]&255;for(c=b=a=0;c<d.length;++c)b|=d[c],a+=!b&!d[c];return d.slice(a-(1&!b))};
U.prototype.toString=function(){var a=[],b=this,c=Td(1E6);do b=Wd(b,c),a.unshift(b.R.a[0]),b=b.W,Xd(b);while(!Yd(b));return a.map(function(d,e){return 0==e||1E6<d?""+d:("000000"+d).slice(-6)}).join("")};var Xd=function(a){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];a.a.length-=b;return a},Zd=function(a){if(0==a.b){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];c=a.a.length-b;b=24*c;c=a.a[c-1];for(c|=!c;0==(c&8388608);)c<<=1,--b;a=a.b=b}else a=a.b;return a};
U.prototype.add=function(a){for(var b=Rd(this.a.length,a.a.length),c=V(b+1),d=0,e=0;e<b;++e)d+=(this.a[e]|0)+(a.a[e]|0),c.a[e]=d&16777215,d>>=24;c.a[b]=d;return c};
var Wd=function(a,b){var c=Zd(b),d=(c+24-1)/24|0;c=24*d-c;b=$d(b,c);var e=Ud(Sd(a.a),$d(a,c),0==c|0);a=Ud(ae,V(e.a.length+1),0>=e.a.length+1-d|0);e.a.push(0);for(var f=e.a.length-d-1;0<=f;f--){var g=b.a.length,h=16777216*e.a[g+f]+e.a[g+f-1];var k=b.a[g-1];var l=Math.floor(h/k);k=l-(16777216==l|l*(b.a[g-2]|0)>16777216*(h-l*k)+(e.a[g+f-2]|0));g=0;a.a[f]=k;for(h=0;h<=d;h++)g+=e.a[h+f]-(b.a[h]|0)*k,e.a[h+f]=g&16777215,g=Math.floor(g/16777216);k=g;g=0;a.a[f]+=k;for(h=0;h<=d;h++)g+=e.a[h+f]+(b.a[h]&k),
e.a[h+f]=g&16777215,g>>=24}if(0>c||23<c)throw new Id("Illegal shift value.");h=e.a.length;b=V(h);f=(1<<c)-1;g=0;for(--h;0<=h;h--)b.a[h]=g+(e.a[h]>>c),g=(e.a[h]&f)<<24-c;c=V(d);for(e=0;e<d;e++)c.a[e]=b.a[e]|0;e=c;Xd(a);return{W:a,R:e}},Yd=function(a){for(var b=ae,c=0,d=0,e=0,f=0,g=Rd(a.a.length,b.a.length)-1;0<=g;--g){var h=a.a[g]|0,k=b.a[g]|0;d|=h<k;c|=h>k&!d;e|=h>k;f|=h<k&!e}return 0==c-f};
U.prototype.and=function(a){for(var b=Rd(this.a.length,a.a.length),c=V(b);0<=b;--b)c.a[b]=(this.a[b]|0)&(a.a[b]|0);return c};U.prototype.or=function(a){for(var b=Rd(this.a.length,a.a.length),c=V(b);0<=b;--b)c.a[b]=this.a[b]|0|a.a[b]|0;return c};U.prototype.xor=function(a){for(var b=Rd(this.a.length,a.a.length),c=V(b);0<=b;--b)c.a[b]=(this.a[b]|0)^(a.a[b]|0);return c};
var $d=function(a,b){if(0>b||23<b)throw new Id("Illegal shift value.");for(var c=a.a.length,d=V(c+1),e=(1<<b)-1,f=(1<<24-b)-1,g=0,h=0;h<c;h++)d.a[h]=((a.a[h]&f)<<b)+g,g=a.a[h]>>24-b&e;d.a[c]=g;return Xd(d)},ae=Td(0);Td(1);Td(2);
var ce=function(a,b){U.call(this,a);Xd(this);a=1;for(var c=this.a[0],d=1;16777216>d;d<<=1)a*c&d&&(a|=d);this.f=16777216-a;if(void 0!==b)b=new U(b);else{b=this.a.length;a=V(2*b+1);for(c=0;c<2*b;++c)a.a[c]=0;a.a[2*b]=1;b=Wd(a,this).R}this.g=b;this.c=be(this,this.g)};t(ce,U);
ce.prototype.pow=function(a,b){a=new U(a);b instanceof U&&(b=Vd(b));var c=W(this,a,this.g);a=Array(16);a[0]=this.c;for(var d=1;16>d;++d)a[d]=W(this,c,a[d-1]);c=V(this.a.length);d=Sd(this.c.a);for(var e=b.length,f=0;f<e;++f)W(this,d,d,c),W(this,c,c,d),W(this,d,d,c),W(this,c,c,d),W(this,d,a[b[f]>>4&15],c),W(this,c,c,d),W(this,d,d,c),W(this,c,c,d),W(this,d,d,c),W(this,c,a[b[f]&15],d);be(this,d,c);return Vd(c)};
var be=function(a,b,c){var d=a.a.length;c=c||V(d);for(var e=0;e<d;++e)c.a[e]=b.a[e];for(e=0;e<d;++e){b=a;var f=c,g=f.a[0],h=g*b.f&16777215;g+=h*b.a[0];for(var k=1,l=b.a.length;k<l;++k)g=(g/16777216|0)+f.a[k]+h*b.a[k],f.a[k-1]=g&16777215;f.a[k-1]=g/16777216|0}de(a,c,d);return c},W=function(a,b,c,d){var e=a.a.length;d=d||V(e);for(var f=0;f<e;++f)d.a[f]=0;for(f=0;f<e;++f){var g=a,h=b.a[f]|0,k=c,l=d,q=h*k.a[0]+l.a[0],w=(q&16777215)*g.f&16777215;q+=w*g.a[0];for(var C=1,ff=g.a.length;C<ff;++C)q=(q/16777216|
0)+h*(k.a[C]|0)+l.a[C]+w*g.a[C],l.a[C-1]=q&16777215;l.a[C-1]=q/16777216|0}de(a,d,e);return d},de=function(a,b,c){for(var d=0,e=0;e<c;++e)d+=b.a[e]-a.a[e],b.a[e]=d&16777215,d>>=24;var f=d>>24;for(e=d=0;e<c;++e)d+=b.a[e]+(a.a[e]&f),b.a[e]=d&16777215,d>>=24};
var ee=function(a,b,c){this.c=a;this.f=this.b=b;this.a=null;this.modulusLength=0;this.a=new ce(a,c);this.modulusLength=Math.ceil(Zd(this.a)/8)};xa(ee,Nd);
var he=function(a,b){this.b=64;this.h=p.Uint8Array?new Uint8Array(this.b):Array(this.b);this.i=this.f=0;this.a=[];this.s=a;this.l=b;this.u=p.Int32Array?new Int32Array(64):Array(64);void 0===fe&&(p.Int32Array?fe=new Int32Array(ge):fe=ge);this.reset()},fe;t(he,Od);var ie=ea(128,ja(0,63));he.prototype.reset=function(){this.i=this.f=0;this.a=p.Int32Array?new Int32Array(this.l):fa(this.l)};
var je=function(a){for(var b=a.h,c=a.u,d=0,e=0;e<b.length;)c[d++]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3],e=4*d;for(b=16;64>b;b++){e=c[b-15]|0;d=c[b-2]|0;var f=(c[b-16]|0)+((e>>>7|e<<25)^(e>>>18|e<<14)^e>>>3)|0,g=(c[b-7]|0)+((d>>>17|d<<15)^(d>>>19|d<<13)^d>>>10)|0;c[b]=f+g|0}d=a.a[0]|0;e=a.a[1]|0;var h=a.a[2]|0,k=a.a[3]|0,l=a.a[4]|0,q=a.a[5]|0,w=a.a[6]|0;f=a.a[7]|0;for(b=0;64>b;b++){var C=((d>>>2|d<<30)^(d>>>13|d<<19)^(d>>>22|d<<10))+(d&e^d&h^e&h)|0;g=l&q^~l&w;f=f+((l>>>6|l<<26)^(l>>>11|l<<21)^(l>>>
25|l<<7))|0;g=g+(fe[b]|0)|0;g=f+(g+(c[b]|0)|0)|0;f=w;w=q;q=l;l=k+g|0;k=h;h=e;e=d;d=g+C|0}a.a[0]=a.a[0]+d|0;a.a[1]=a.a[1]+e|0;a.a[2]=a.a[2]+h|0;a.a[3]=a.a[3]+k|0;a.a[4]=a.a[4]+l|0;a.a[5]=a.a[5]+q|0;a.a[6]=a.a[6]+w|0;a.a[7]=a.a[7]+f|0};
he.prototype.c=function(a,b){void 0===b&&(b=a.length);var c=0,d=this.f;if("string"===typeof a)for(;c<b;)this.h[d++]=a.charCodeAt(c++),d==this.b&&(je(this),d=0);else if(m(a))for(;c<b;){var e=a[c++];if(!("number"==typeof e&&0<=e&&255>=e&&e==(e|0)))throw Error("t");this.h[d++]=e;d==this.b&&(je(this),d=0)}else throw Error("u");this.f=d;this.i+=b};
he.prototype.g=function(){var a=[],b=8*this.i;56>this.f?this.c(ie,56-this.f):this.c(ie,this.b-(this.f-56));for(var c=63;56<=c;c--)this.h[c]=b&255,b/=256;je(this);for(c=b=0;c<this.s;c++)for(var d=24;0<=d;d-=8)a[b++]=this.a[c]>>d&255;return a};
var ge=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,
4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];
var le=function(){he.call(this,8,ke)};t(le,he);var ke=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225];
for(var me=[1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,1555081692,3175218132,
1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,1432725776,4094571909,
1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,174292421,2731055270,
289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591],ne=[],oe=0;oe<me.length;oe+=2)ne.push(new R(me[oe+1],me[oe]));
var pe=function(){this.b=-1};t(pe,Od);pe.prototype.reset=function(){this.a.reset()};pe.prototype.g=function(){return this.a.g()};pe.prototype.c=function(a,b){this.a.c(a,b)};pe.prototype.hash=function(a){this.reset();this.c(a);return this.g()};
var qe=function(){this.b=-1;this.a=new le;this.b=this.a.b};xa(qe,pe);qe.prototype.f="SHA256";
var re=function(a){u.call(this,a)};xa(re,u);
var se={MD5:[48,32,48,12,6,8,42,134,72,134,247,13,2,5,5,0,4,16],RIPEMD160:[48,33,48,9,6,5,43,36,3,2,1,5,0,4,20],SHA1:[48,33,48,9,6,5,43,14,3,2,26,5,0,4,20],SHA224:[48,45,48,13,6,9,96,134,72,1,101,3,4,2,4,5,0,4,28],SHA256:[48,49,48,13,6,9,96,134,72,1,101,3,4,2,1,5,0,4,32],SHA384:[48,65,48,13,6,9,96,134,72,1,101,3,4,2,2,5,0,4,48],SHA512:[48,81,48,13,6,9,96,134,72,1,101,3,4,2,3,5,0,4,64]};
var te=function(a,b,c,d){ee.call(this,a,b,c);this.g=d||new qe};xa(te,ee);
var ue=function(a,b,c,d){this.a=null;this.b=new te(a,b,c,d)};xa(ue,Md);
var ve=function(a){this.a=a};
var we=function(a,b){this.a=new ve(new ue(a,b))};
var xe=function(a,b,c,d,e){this.a="U";this.b=0;a&&(a=a.split(","))&&2==a.length&&(this.a=a[0],this.b=parseInt(a[1],10));if(0>=b||0>=c||0>=d)throw Error("v");this.h=b;this.c=c;this.g=d;this.f=e},ye=function(a){switch(a.a){case "Y":return a.h;case "N":return a.c;case "P":return a.f;default:return a.g}},ze=function(a,b,c,d,e,f){this.g=new we(Db(a),Db(b));this.f=c;this.a=d;this.c=e;this.b=f};
var Ae=function(a,b,c,d,e,f,g,h){this.a=a||"";this.b=new ze(b||"",c||"",e||1,f||1,g||1,h||1);this.c=d||""},Be=function(a){var b=(new Q(document)).get(a.a,"");if(b){var c=a.b;var d=c.g;a=Ka(a.c);b=Db(b.substr(b.indexOf(":")+1));d=d.a;var e=d.a;if(!e.a){var f=new Pd;f.c(Jd([e.b.c.length]));f.c(e.b.c);f.c(Jd([e.b.b.length]));f.c(e.b.b);f=f.g();var g=Array(5);g[0]=0;g[1]=f[0];g[2]=f[1];g[3]=f[2];g[4]=f[3];e.a=g}e=e.a;b:if(f=ia(b,0,e.length),m(e)&&m(f)&&e.length==f.length){g=e.length;for(var h=0;h<g;h++)if(e[h]!==
f[h]){f=!1;break b}f=!0}else f=!1;if(f){f=e.length+4;e=ia(b,e.length,f);g=[];for(h=0;h<e.length;h+=4)g.push((e[h+3]|e[h+2]<<8|e[h+1]<<16|e[h]<<24)>>>0);g=g[0];if(f+g>b.length)b=null;else{e=ia(b,f,f+g);a=ka(e,Jd([a.length]),a,b[0]);d=d.a.b;b=d.a.pow(ia(b,f+g),d.f);f=d.g;d=d.modulusLength-1;g=f.hash(a);a=[];if(void 0===se[f.f])throw new re("invalid hash for signature");ha(a,se[f.f]);ha(a,g);f=a.length;if(d<f+11)throw new re("intended encoded message length too short");a=[1].concat(ja(255,d-f-3+1),[0],
a);if(a.length===b.length&&Kd(a)&&Kd(b)){d=1;for(f=0;f<a.length;f++)d&=!(a[f]^b[f])|0;b=1==d}else b=!1;b=b?e:null}}else b=null;if(b)if(8192>=b.length)b=String.fromCharCode.apply(null,b);else{a="";for(d=0;d<b.length;d+=8192)a+=String.fromCharCode.apply(null,ia(b,d,d+8192));b=a}else b=null;c=new xe(b,c.f,c.a,c.c,c.b)}else c=null;return c?"Y"==c.a&&!(c.b+ye(c)<Date.now()):!1};
var Ce=function(a,b,c,d,e,f){try{var g=a.a,h=Oc(a.a,"SCRIPT");h.async=!0;h.src=Va(b);fb(h);g.head.appendChild(h);h.addEventListener("load",function(){e();d&&g.head.removeChild(h)});h.addEventListener("error",function(){0<c?Ce(a,b,c-1,d,e,f):(d&&g.head.removeChild(h),f())})}catch(k){f()}};
var De=function(a){return a?Wa(B(a,4)||""):null},Ee=function(a){return a?new v(B(a,3)||"",ab):null};
var Ge=function(a){A(this,a,Fe,null)};t(Ge,z);var Fe=[2],He=function(){var a=new Ge;a=E(a,1,0);B(a,2).push(1);return a};
var Ie=function(a){A(this,a,null,null)};t(Ie,z);var Je=function(a){A(this,a,null,null)};t(Je,z);
var Ke=function(a){a=(void 0===a?null:a)||p;return a.googlefc||(a.googlefc={})},X=function(a,b,c){c=void 0===c?!1:c;var d=Ke(null);if(!d.hasOwnProperty(a)||c)d[a]=b};
var Le={UNKNOWN:0,CONSENTED_TO_PERSONALIZED_ADS:1,CONSENTED_TO_NON_PERSONALIZED_ADS:2,CONTRIBUTOR:3,NO_CONSENT:4,CONSENT_NOT_REQUIRED:5},Me={UNKNOWN:0,EXTENSION_LEVEL_AD_BLOCKER:1,NETWORK_LEVEL_AD_BLOCKER:2,NO_AD_BLOCKER:3},Ne={UNKNOWN:0,NOT_WHITELISTED:1,WHITELISTED:2},Oe={UNKNOWN:0,ADS_NOT_ALLOWED:1,ADS_ALLOWED:2},Pe={},Qe=(Pe.AD_BLOCK_DATA_READY=1,Pe.CONSENT_DATA_READY=2,Pe.INITIAL_CCPA_DATA_READY=3,Pe);X("ConsentStatusEnum",Le);X("AdBlockerStatusEnum",Me);X("WhitelistStatusEnum",Ne);
X("AllowAdsStatusEnum",Oe);
var Re=function(a){A(this,a,null,null)};t(Re,z);
var Te=function(a){A(this,a,Se,null)};t(Te,z);var Se=[1];
var Ue=function(a){A(this,a,null,null)};t(Ue,z);
var Ve=function(a){A(this,a,null,null)};t(Ve,z);var We=function(a){A(this,a,null,null)};t(We,z);var Xe=function(a){A(this,a,null,null)};t(Xe,z);
var Ye=function(a,b){this.b=a;this.c=b;this.a=!1},Ze=function(a){if(!a.a){var b=a.c,c=new I,d=new H;var e=new Ub;e=E(e,1,!0);P(b,J(c,G(d,5,e)));a.a=!0}switch(a.b){case 1:return Me.EXTENSION_LEVEL_AD_BLOCKER;case 2:return Me.NETWORK_LEVEL_AD_BLOCKER;case 3:return Me.NO_AD_BLOCKER;default:return Me.UNKNOWN}};
var $e={},af=($e.adBlockData="AD_BLOCK_DATA_READY",$e.consentData="CONSENT_DATA_READY",$e.initialCcpaData="INITIAL_CCPA_DATA_READY",$e),bf=function(a){this.f=0;this.g=a;this.b={};this.a={};this.c={}};
bf.prototype.push=function(a){if("object"===typeof a){for(var b in af){var c=af[b];if(a[c]){var d=b;var e=a[c];break}}d||(d="unrecognizedData",window.console.error("Unrecognized data availability type in the queued FC callback",Object.keys(a)[0]))}else d="legacyNoData",e=a;if("unrecognizedData"!==d&&!this.c[d])return this.a[d]=this.a[d]||[],this.a[d].push(e);a=!1;if("function"===typeof e)try{e(),this.f++}catch(f){window.console&&window.console.error&&window.console.error("Exception in queued FC callback",
f),a=!0}if(!this.b[d]){e=d;b=new Rb;a=E(b,1,a);switch(e){case "legacyNoData":E(a,2,!0);break;case "adBlockData":E(a,4,!0);break;case "consentData":E(a,3,!0);break;case "initialCcpaData":E(a,6,!0);break;case "unrecognizedData":E(a,5,!0)}e=new I;b=new H;a=G(b,1,a);e=J(e,a);P(this.g,e);this.b[d]=!0}return this.f};bf.prototype.executeRemainingFunctions=function(a){this.c[a]=!0;for(var b=af[a],c=qa(this.a[a]||[]),d=c.next();!d.done;d=c.next()){d=d.value;var e={};this.push(b?(e[b]=d,e):d)}delete this.a[a]};
var cf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=Ke().callbackQueue;if(e&&!Array.isArray(e))d=e;else{d=new bf(a);X("callbackQueue",d,!0);e=qa(e||[]);for(var f=e.next();!f.done;f=e.next())d.push(f.value)}c=qa(c);for(e=c.next();!e.done;e=c.next())d.executeRemainingFunctions(e.value)};
var df=function(a){try{var b=nd(a);return b?Lb(pd,b):null}catch(c){return null}};
var ef=function(a,b){this.a=a;this.f=b;this.c=this.b=!1},gf=function(a){if(!a.b){var b=a.f,c=new I,d=new H;var e=new Tb;e=E(e,1,!0);P(b,J(c,G(d,4,e)));a.b=!0}if((b=(b=ld(document))?F(b,hd,4):null)&&null!=B(b,1)&&B(b,1)||null===a.a)return Le.UNKNOWN;if(null!=a.a&&!a.a)return Le.CONSENT_NOT_REQUIRED;a=df(document);return a?(b=B(a,2))&&b.length?Le.CONSENTED_TO_NON_PERSONALIZED_ADS:(a=B(a,1))&&a.length?Le.CONSENTED_TO_PERSONALIZED_ADS:Le.UNKNOWN:Le.NO_CONSENT};
var hf=y?Wa(Ra(new Qa(Oa,'javascript:""'))):Wa(Ra(new Qa(Oa,"about:blank"))),jf=function(){this.a=new Pc(p.top.document)},lf=function(a){if(!kf(a)){var b=Oc(a.a.a,"IFRAME");b.name="googlefcInactive";b.src=Va(hf).toString();b.style.display="none";b.style.width="0px";b.style.height="0px";b.style.border="none";b.style.zIndex="-1000";b.style.left="-1000px";b.style.top="-1000px";var c=function(){a.a.a.body?a.a.a.body.appendChild(b):p.setTimeout(c,5)};c()}},kf=function(a){return Ja(a.a.a.getElementsByTagName("IFRAME"),
function(b){return"googlefcInactive"===b.name})};
var mf=function(a,b){this.f=this.l=this.c="";this.i=null;this.g=this.h="";this.a=!1;if(a instanceof mf){this.a=void 0!==b?b:a.a;nf(this,a.c);this.l=a.l;this.f=a.f;of(this,a.i);this.h=a.h;b=a.b;var c=new Y;c.c=b.c;b.a&&(c.a=new M(b.a),c.b=b.b);pf(this,c);this.g=a.g}else a&&(c=String(a).match(Rc))?(this.a=!!b,nf(this,c[1]||"",!0),this.l=qf(c[2]||""),this.f=qf(c[3]||"",!0),of(this,c[4]),this.h=qf(c[5]||"",!0),pf(this,c[6]||"",!0),this.g=qf(c[7]||"")):(this.a=!!b,this.b=new Y(null,this.a))};
mf.prototype.toString=function(){var a=[],b=this.c;b&&a.push(rf(b,sf,!0),":");var c=this.f;if(c||"file"==b)a.push("//"),(b=this.l)&&a.push(rf(b,sf,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.i,null!=c&&a.push(":",String(c));if(c=this.h)this.f&&"/"!=c.charAt(0)&&a.push("/"),a.push(rf(c,"/"==c.charAt(0)?tf:uf,!0));(c=this.b.toString())&&a.push("?",c);(c=this.g)&&a.push("#",rf(c,vf));return a.join("")};
var nf=function(a,b,c){a.c=c?qf(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},of=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("w`"+b);a.i=b}else a.i=null},pf=function(a,b,c){b instanceof Y?(a.b=b,wf(a.b,a.a)):(c||(b=rf(b,xf)),a.b=new Y(b,a.a))},yf=function(){var a=p.location.href;return a instanceof mf?new mf(a):new mf(a,void 0)},qf=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},rf=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,
zf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},zf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},sf=/[#\/\?@]/g,uf=/[#\?:]/g,tf=/[#\?]/g,xf=/[#\?@]/g,vf=/#/g,Y=function(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b},Z=function(a){a.a||(a.a=new M,a.b=0,a.c&&Sc(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};
Y.prototype.add=function(a,b){Z(this);this.c=null;a=Af(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};var Bf=function(a,b){Z(a);b=Af(a,b);N(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,N(a.b,b)&&(delete a.b[b],a.c--,a.a.length>2*a.c&&Lc(a)))},Cf=function(a,b){Z(a);b=Af(a,b);return N(a.a.b,b)};Y.prototype.forEach=function(a,b){Z(this);this.a.forEach(function(c,d){Ia(c,function(e){a.call(b,e,d,this)},this)},this)};
Y.prototype.o=function(){Z(this);for(var a=this.a.m(),b=this.a.o(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};Y.prototype.m=function(a){Z(this);var b=[];if("string"===typeof a)Cf(this,a)&&(b=ea(b,this.a.get(Af(this,a))));else{a=this.a.m();for(var c=0;c<a.length;c++)b=ea(b,a[c])}return b};Y.prototype.set=function(a,b){Z(this);this.c=null;a=Af(this,a);Cf(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
Y.prototype.get=function(a,b){if(!a)return b;a=this.m(a);return 0<a.length?String(a[0]):b};Y.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.o(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.m(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.c=a.join("&")};
var Af=function(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b},wf=function(a,b){b&&!a.f&&(Z(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Bf(this,d),Bf(this,e),0<c.length&&(this.c=null,this.a.set(Af(this,e),fa(c)),this.b+=c.length))},a));a.f=b};
var Df=function(){var a=yf().b.get("fcconsent");var b=yf().b.get("fc");return"alwaysshow"===b?b:"alwaysshow"===a?a:null};
var Ef=function(a,b){this.a=a;this.c=new jf;this.b=new qd(this.a,b)};
var Ff=function(a,b,c,d,e,f,g){this.a=a;this.h=c;this.g=d;this.c=b;this.f=e;this.l=new Ef(document,f?f:p.location.hostname);this.i=g;this.b=!1},Hf=function(a){sd(a.l.b);a.b||(P(a.i,J(new I,Wb())),a.b=!0);if(Be(new Ae(B(a.a,1),B(a.a,5),B(a.a,4),B(a.a,6),B(a.a,8),B(a.a,9),B(a.a,10),B(a.a,11))))gb(a.f);else{var b=a.c;b={};var c=Df();c&&(b.fc=c);var d=He();b.cp=d.g();b.fccs=Gf(c,d);b=Ya(a.c,b);Ce(new Pc(document),b,3,!1,function(){},function(){})}},Gf=function(a,b){var c=new Ie;b=G(c,11,b);c=new Date(Date.now());
var d=new Qb;Ib(d,1,Math.floor(c.getTime()/1E3));Ib(d,2,1E6*c.getMilliseconds());b=G(b,7,d);a&&(a=new Je,a=E(a,1,1),G(b,10,a));a=b.g();return Bb(Ka(a),4)};
var If=function(a,b){this.c=a;this.b=b;this.a=!1},Jf=function(a){if(!a.a){var b=a.b,c=new I;var d=new H;var e=Vb();d=G(d,5,e);P(b,J(c,d));a.a=!0}switch(a.c){case 2:return Ne.WHITELISTED;case 1:return Ne.NOT_WHITELISTED;default:return Ne.UNKNOWN}},Kf=function(a){if(!a.a){var b=a.b,c=new I;var d=new H;var e=Vb();d=G(d,5,e);P(b,J(c,d));a.a=!0}switch(a.c){case 2:return Oe.ADS_ALLOWED;case 1:return Oe.ADS_NOT_ALLOWED;default:return Oe.UNKNOWN}};
var Lf=function(a,b,c,d,e,f,g){this.c=a;this.b=b;this.h=c;this.g=d;this.f=e;this.i=f;this.a=g};
Lf.prototype.load=function(a,b,c,d){var e=new Ye(b,this.a),f=new If(c,this.a);if(d===Qe.AD_BLOCK_DATA_READY||d===Qe.CONSENT_DATA_READY){var g=new ef(a,this.a);X("getConsentStatus",function(){return gf(g)});X("getConsentedProviderIds",function(){var k=df(document);if(!g.c){var l=g.f,q=new I,w=new H;var C=new Tb;C=E(C,2,!0);w=G(w,4,C);P(l,J(q,w));g.c=!0}return k?B(k,1):[]});X("getAdBlockerStatus",function(){return Ze(e)});X("getWhitelistStatus",function(){return Jf(f)});X("getAllowAdsStatus",function(){return Kf(f)});
var h=new Ff(this.c,this.b,this.h,this.g,this.f,this.i,this.a);X("getDefaultConsentRevocationText",function(){return h.h});X("getDefaultConsentRevocationCloseText",function(){return h.g});X("showRevocationMessage",function(){return Hf(h)});cf(this.a,"consentData","legacyNoData")}d===Qe.AD_BLOCK_DATA_READY&&(X("getAdBlockerStatus",function(){return Ze(e)},!0),X("getWhitelistStatus",function(){return Jf(f)},!0),X("getAllowAdsStatus",function(){return Kf(f)},!0),cf(this.a,"adBlockData"))};
var Mf=function(a){this.a=a;this.b=new dd(F(this.a,Zb,4))},Nf=function(a){return(a=B(a.a,8))?a:""},Of=function(a){return(a=B(a.a,9))?a:""},Pf=function(a,b,c,d,e){var f=Qe.AD_BLOCK_DATA_READY;(new Lf(F(a.a,ed,2),De(F(a.a,Zb,1)),Nf(a),Of(a),Ee(F(a.a,Yb,3)),c,a.b)).load(b,d,e,f)};
var Qf=function(a){this.a=a};
var Rf=function(a){this.a=a},Sf=function(a){this.a=a};
var Tf=function(a,b,c,d){this.h=a;this.g=b;this.c=c;this.a=d;this.f=F(this.c.a,Ge,6);a=this.g;b=this.h.location.hostname;this.b=null!=B(a.a,2)&&""!=D(a.a,2,"")?D(a.a,2,""):b;this.i=new qd(p.document,this.b);this.l=new Ef(this.h.document,this.b);this.s=new Qf(this.h)};
(function(a,b){p[a]=function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];p[a]=Da;b.apply(null,d)}})("__8v31i8woen1z__",function(a,b){b=Lb(Ve,b);a=new Tf(a,new Rf(F(b,We,1)),new Mf(F(b,Ue,3)),new Sf(F(b,Xe,4)));b=a.s;var c=F(a.c.a,Te,10);if(c){var d=b.a.__fcTrace;d=d?Lb(Te,d):new Te;Jb(c,Re);var e=c.a[1];e==Fb&&(e=c.a[1]=[]);c=qa(e);for(e=c.next();!e.done;e=c.next()){var f=e.value,g=Re;Jb(d,g);(e=d.a[1])||(e=d.a[1]=[]);f=f?f:new g;g=B(d,1);e.push(f);g.push(f.j)}b.a.__fcTrace=d.g()}D(a.g.a,
3,"")&&(b=a.i,c=D(a.g.a,3,""),d=td(b),e=new fd,c=E(e,1,c),G(d,1,c),ud(b,d));b=B(a.f,2);if(b.includes(2)||b.includes(3)||b.includes(9)||b.includes(8)||b.includes(11)||b.includes(10)){var h=0===D(a.f,4,0)?null:1===D(a.f,4,0);b=D(a.a.a,1,0);d=D(a.a.a,2,0);Pf(a.c,h,a.b,b,d)}else{b=a.l;d=df(b.a)||new pd;lf(b.c);E(d,7,!0);b=b.b;e=d.g();c=!0;c=void 0===c?!1:c;d=td(b);c=c&&Ob(d)?43200:33696E3;f=new gd;f=E(f,1,e);f=E(f,2,Date.now());G(d,3,f);a:if(e){try{h=Lb(pd,e)}catch(k){h=!1;break a}h=B(h,7);h=!!h}else h=
!1;h||(G(d,5,void 0),G(d,4,void 0));ud(b,d,c);jd(b.a,"DATA_USE_CONSENT",b.b);h=D(a.a.a,1,0);b=D(a.a.a,2,0);Pf(a.c,!1,a.b,h,b)}});

}catch(e){_._DumpException(e)}
}).call(this,this.default_ContributorServingCookieRefreshClientJs);
// Google Inc.

//# sourceURL=/_/mss/boq-content-ads-contributor/_/js/k=boq-content-ads-contributor.ContributorServingCookieRefreshClientJs.en_US.nlW9H95ali8.es5.O/d=1/ct=zgms/rs=AJlcJMwJl1ZhCrWxD6WM7oW2X0txdk5-lw/m=cookie_refresh
__8v31i8woen1z__(window, '\x5b\x5bnull,\x22www.tecmundo.com.br\x22,\x22AKsRol_lqg75J7jFv42qp7NZUPMI740j43WlYxWK-0qIMgYIkPcLcGlWmtXA3rXmMgxj4lxh0sDCkNnw9uTy30H-X0DpqPzH_wxZnP7OWtfiXFX1NKrDrpSILenerDRbVEk-DPhdGQcvTirAssc2atUDNDP4ZZoHuQ\\u003d\\u003d\x22\x5d\n,null,\x5b\x5bnull,null,null,\x22https:\/\/fundingchoicesmessages.google.com\/f\/AGSKWxUpZslxBxsrzxCaetciJi_73TPWqlpDVBVddzCAI8SIC_EYKHdaY488m9Y066OnutNhAf4KLfoR3SXcVGBCmhwUi8UXnFUYQByghONvvjeMhXV38qjcGlY4ig0vGo_O2pYVTUxcqpowDsZ7XYI06amNcJaTo9slvz_L9hRHI29-enOYVgaivhLy6-nR\x22\x5d\n,\x5b\x22CUID\x22,null,null,\x22AQAB\x22,\x22xjD+3n\/2dg9f5UFAIUf+4vhZGQSc3EKhdetwa27dV0LLb7Zaz7wBF\/SXgtNL80fjtys+pjga5cZ+hTgxiDHbJk6YsXdvn3RFjC0nouxhz+il+qlBpIGJETnaCxFtdQqZ6wVtueQ64kY7BCLXdpk7fbHfwWa2gOafE4cVgn5XtzEnmiLHLQHM+7TU\/irBxLp+KkCRJlRWktsOUselftldaTo43Qg8FNZqPYn2ZS\/Z21\/1dDu8Ih5GSCMIUL53grRXCKbqh8oSujJbCTcBQX1oWQW7yd\/FSTt9fD8GH85LUlkhtwXBdqrdkg2oTVDqxjXGwZsf6AfLb3I42OvYYjJHmQ\\u003d\\u003d\x22,\x22cde182d65009d9cb\x22,\x22refcon\x22,900000,60000,60000,86400000,\x22P,1599847536438:ALHGLuQAAAAPUCwxNTk5ODQ3NTM2NDM4QlkQRkUvjfZA5uFP+F62lrNvWwYFCfSghyg\/m8DQsH6Cx0kZMokpcxM9tmL\/CCx4GOPkdQqn5YYg2awIgjbUxvivB8TFvgrjLKvwElI\/75CBN\/OqHUJoFcPS57J\/L5nC7JGJTsGMcYi0TOpR5\/HSy+Sj+5823L9c1RvSVnORxeAEREH+12uGGKVrZ62+KBWxy6rGgGKA55eNDRmEiWclsS4wei4pA+m8W9\/x5X4WbHmZ9WHx\/gmVkS2R+eNKW5FDF1GUw+JnNeSbMsMCHDsealohaUw9Y6UeTNPRRYJ5ETN90UKBJ7B2BCWu17UfjEU0EpyF2+mE4RnY3UPKBRwJwA\\u003d\\u003d\x22,2592000\x5d\n,\x5bnull,null,\x22https:\/\/support.google.com\/contributor\/answer\/7687985\x22\x5d\n,\x5bnull,null,null,\x22https:\/\/fundingchoicesmessages.google.com\/l\/AGSKWxUZ7f1Y6ki07ySXIpmk9s9bfhy4ZVCh7UJF6wcWla8h0ra_P35YlbMT_NtGUeKJg0vLqupS03iHBT0riPVqvATZcCQ7KpxDY8ntYsiRglwpxOYCaYf21vI9OYnXDpjvKy059y22abYvo_J30j0yeCc0wrjEmNnY1udbWbKNLrVCzGcmOQtq8ZtW1bHE\x22\x5d\n,null,\x5b1,\x5b7,6\x5d\n\x5d\n,null,null,null,null,null,\x22cde182d65009d9cb\x22\x5d\n,\x5b3,1\x5d\n\x5d\n');